---
title: "Customizing the Webpage"
---

There are many things you can do to customize your webpage. Here we will go over some of them.

The first thing is to customize the navigation bars. There are two types of navigation bars: horizontal and vertical.
The horizontal navigation bars are the tabs you already see on your webpage. In addition, you can have vertical navigation bars, which are on the side.

To create the tabs on the top, you add this text to your yml file under the website attribute:
"navbar:
    tools:
        menu:
          - about.qmd
          - index.qmd"
          
To create the vertical navigation option, you add this text to your yml file under the website attribute:
"sidebar:
    contents:
      - about.qmd
      - index.qmd"
      
It is possible to have only one at a time or both together (which I will get back to later).

In addition, there are many options to customize the navigation bars:
- You can add items under "left" or "right" under "navbar" to specify on which side of the navbar it should be built
- You can add headers without a link, just some text by just using the "text" attribute and no "href". This could for example be "text: Heading 1" or just "text: ------" to create a separation bar
- It is possible to make many more customizations by defining the navbar in html code instead of in the yml header. This does however require writing out more manually and can be harder to figure out. Here is an example of a [navbar written in html](https://github.com/rstudio/rmarkdown-website/blob/master/_navbar.html).
- If you do not want your title displayed in the navbar, you can add "title: false" under navbar and it will not just use the site name as default, but rather leave it blank
- "logo" allows you to add a logo to the navbar
  - "logo-alt" provides the alternative text for the logo for individuals who are using a program reading the visuals out loud
- You can change the backgroun color of the navigation bar with "background", which can be set to “primary”, “secondary”, “success”, “danger”, “warning”, “info”, “light”, “dark”, or hex color. The color associated with these attributes depend on the colors used by your template. Check the colors of your theme [here](https://bootswatch.com/).
- "foreground" colors the navigation bar items, texts, and links
- "search" includes a search bar, with values as "false" or "true"
- "tools" can add buttons or other choices to navigate to sites (e.g. social media). If you turned on dark and light mode, the button for that will have appeared as a tool. Tools always show up on the right side of the navigation bar.
  - Many of the tools have an icon, which you can add with "icon" by specifying for example on of the icons from Bootstrap. Then you also want to add "href" with the link to be added to the icon. You can also create a pull-down menu from your icon, by adding an icon and a "menu" instead of the "href". Then under "menu", you can add "href" and "text" for additional links to add. However, note that the positioning of tools is not always good. I made a pull-down bar where part of the text went out of the page. This probably mean that the code for tools is not as well-made as the code for other attributes as "left" and "right". I therefore suggest using "right" instead of "tools" always, to get around this problem. Everything is the same, just with "right" instead of "tools".









In the _quarto.yml file, you can change the margin on the pages. Add "    page-layout: article" under "format and html". By default (if you don't specify page-layout), it will use article, which leaves about 7 cm of white space on the right side of the screen when you open each page. You can change it to full, which makes the text use all of the page. If you are like me, you would like something in-between, you can remove the page-layout option and instead add "grid:" with the suboption "margin-width: 100px". The higher the number, the more white space you will get on the right side of the screen. You can also customize the size of the other sizes under the grid attribute, such as "sidebar-width" (the navigation bar on the side), "body-width" (the size of the area with your main text), and "gutter-width" (the size between each area, such as the navigation bar,the body of the text, and the table of contents). If you start changing one of these options though, that will shift everything. So it is better to either just use "page-layout" or all of the four page options. This webpage uses the following values:
"    grid:
      sidebar-width: 275px
      body-width: 2000px
      margin-width: 100px
      gutter-width: 1rem"


Changing the title of the pages
You can change the title of the qmd file in the yml header and this is then the title that will be displayed both in the navigation bar and on the webpage. If you for some reason want to display a different name in the navigation bar than on the page, you can change this in the navigation bar. So far, you have in your _quarto.yml document used a dash (-) and the file name to add to the navigation bar. If you want a different title, you can split an entry up and change for example "- about.qmd" to:
"- text: "About"
   href: about.qmd"

Changing the themes of the webpage
Quarto has several built-in themes that you can use to change the colors and font of your webpage. You can see the built in options [here](https://bootswatch.com/). By default, Quarto uses Cosmo, but you can change that to any of the other themes. I have for example used the theme Flatly for this webpage. You can even have a webpage for light and one for dark mode. To do this, use the following code:
"theme:
      light: flatly
      dark: darkly"
This creates a toggle in your top nav bar where users can switch between dark and light mode.

You might have noticed that Quarto chooses two themes by defualt: cosmo and brand. Brand is not a default theme, so I think this is an option to create your own customized options in a brand document that then gets linked. If you plan on doing this, you might want to keep the "brand", if not, you can safely delete it. Here is further information about creating your own [brand document](https://quarto.org/docs/authoring/brand.html).

Changing the themes of the webpage affects the color choices. If you have a top navigation bar (with tabs) this will for example by default go to the "light" option in your theme. Most of the themes are made to instead use the "primary" color, so you can change this the color of the nav bar to primary, or any other color in your theme, by adding "background: primary" under navbar in the _quarto.yml file.

You can also change the color of the side bar with the same background option, but this can create some challenges with the margins being white, so it does typically look better to keep it as the same color as the background color.

You can further customize the templates you are using by adding your own theme file, for example as "light: [flatly, theme.scss]". The options to include in the scss file can easily be googled to further customize the page, for example with a different link color. I have just stuck with the theme, so I have not explored this further. If you are interested in doing these further customizations though, check out the [Quarto documentation page](https://quarto.org/docs/output-formats/html-themes.html) and [this course in advanced sutomization usin SASS](https://ucsb-meds.github.io/customizing-quarto-websites/#/title-slide). 


Linking to other pages
You can link to a different page on a page the same way you would link to a URL. You use square brackets around the text you want displayed over the link, then without any spaces, you have a parenthesis with the file name for the page you want to link to, such as about.qmd. You can see it in action [here](about.qmd). If you have headings and sections formatted on the page, you can also link to that specific page by adding #section_name right after the file name. If I had for example had a section for "cv" on my about page, linking to that section would look like this "about.qmd#cv".


Create a web tab icon
You can specify an icon that will be displayed in the tab of the webpage when people look at your webpage. To add this, you first need to get a png file with the icon or logo you want, preferrably with a transparent background. Then, save it in your project folder. I recommend making a separate folder for pictures, for example called "pics". Then add the favicon attribute under webpages with the link to get from where your R project file is to the picture you want and the file name of the picture. In my case, it looks like the following:
"website:
   favicon: pics/logo/Binary_code.png"









SOURCES
- Customizing Rmarkdown documents - [Link](https://rstudio4edu.github.io/rstudio4edu-book/doc-dress.html)
- Customizing Quarto webpages - [Link](https://quarto.org/docs/websites/website-navigation.html#side-navigation)
- Introduction to creating a Quarto webpage, hosting it on GitHub, and customizing the page - [Link](https://ucsb-meds.github.io/creating-quarto-websites/)
- Instructions on customizing the layout of a Quarto document (or page) - [Link](https://quarto.org/docs/output-formats/page-layout.html)
- Values for the page layout - [Link](https://forum.posit.co/t/how-to-control-the-left-and-right-empty-space-on-quarto-blog/169633/3)
- Overview of the built-in Quarto themes - [Link](https://bootswatch.com/)
- Overview of some Quarto webpage customizations, such as navbars - [Link](https://bookdown.org/yihui/rmarkdown/rmarkdown-site.html)