---
title: "Making the Webpage"
---

The following page will detail how to make a webpage with Rstudio that is hosted online through Git Hub. The web page can then be visited by other people by using your URL, just like you are doing on this web page. The steps to set it up are relatively easy, but they do require a little bit of back and forth. Once you have created the webpage, it is easier to work on it. The first steps are therefore the most time consuming.

In the following tutorial, I will use the following programs:
- Rstudio
- GitHub
- Optional: Git terminal

You can create a webpage just by using Quarto (or Rmarkdown). However, when you render your webpage, it will just be saved locally on your computer, so other people cannot access the webpage unless they also have all the files that you have. You have therefore then only created the internal structure of the webpage and not published it online. To get it online so that other people can access it, you have to save your work in a Git repository that is hosted on GitHub and then publish the pages through GitHub. Your webpage will then get an URL with the word github in it, as it is hosted on github.

Creating a webpage in Quarto is very easy. Likewise, creating a Git repository is also very easy. Unfortunately, creating a webpage that is also a repository and getting them to talk to each other is more complicated. However, this guide will walk you through it, so just be patient with it and we will get there together.

The first step is to make a Git repository. It is also possible to make the webpage first (which makes making the webpage easier, but that creates more steps in GitHub and as Rstudio is easier to understand and navigate than GitHub, I would rather take extra steps in Rstudio than in GitHub). If you however are dead set on creating the webpage first and then the repository, this link might be helpful: https://happygitwithr.com/existing-github-first. Personally, I saw others online indicating that it is easier to make the repository first, so I just deleted my R project and started with the repository.

So, make the repository in GitHub first.

Then, you want to add a R project to the repository in Rstudio. To do this, open Rstudio, create a new project, and chose "Version Control" and then "Git". Then it asks you for the URL of the remote repository. You can get this by going to your repository in GitHub and clicking the green "Code" button. This will show you a link starting with https. Copy the link and paste it into the box in Rstudio. The name of the project will then automatically update to the name of your repository from the link. Then you chose where to save this project and the local repository in your files.

Now, you have created a local repository. However, the new files (such as .gitignore and your r project file) are not included in your local repository by git yet, so you need to stage these files, commit them, and push them to the remote repository.

Then you can start getting the internal structure of the webpage into your folder. There are two ways to do this, and I recommend the second one.
1. You can create the necessary files: _quatro.yml, about.qmd, index.qmd, styles.css, and _site. They do not have a lot of content, so this is not impossible to do
2. You can create a new R project (that you later delete) and choose "Quarto website" of the options. Then by using file explorer, you can copy the above mentioned files and folders and paste them into the R project for your webpage. Then you can delete the R project you just created to get the files, for example in file explorer. If you are planning on creating multiple webpages, you can save these files in a folder and copy these to the relevant R projects as you create webpages. Then you won't have to always create a new temporary R project and delete it later.

When you have the files in the R project, open _quarto.yml in Rstudio and find the top section that says:
"project:
  type: website"

add the line "output-dir: docs" so that it now says:
"project:
  type: website
  output-dir: docs"

We do this because your output files (html) that gets shown on your webpage are saved in the _site folder by Rstudio initially, but GitHub expects a folder called "Docs", so we need to tell Rstudio to create the folder "Docs" and save the output pages there, so that GitHub will find them.

In addition, you want to create a new document and save it with the file name .nojekyll. The document does not need anything else, just save a blank document with that file name. After the file is saved, it might disappear from your view in Rstudio, that is ok, it is still there. This file tells GitHub to not use jekyll for making webpages, but instead html, which is what we will create in Rstudio.

After you have done all this, you can build your webpage. On the top right pane in Rstudio, you can see a tab called "Build". Click on this tab and click on "Render Website". It will take a litle bit and then a new window will open showing you the webpage you have so far. This is the local webpage, meaning that you have now made your webpage, but that it is not hosted online yet. Stage, commit, and push these changes now.

The next step is then to host the webpage online. To do this, go to GitHub and your repository. Click on the "Settings" tab and scroll down to "Pages" on the left side. Where it says "None", click on it and select "Main". Then next to it, click on the scroll down menu and select "Docs". Then click "Save" and wait for GitHub to create the webpage. This might take some time. When the webpage is created, you will see a green banner and the "Pages" page will also update to have your URL. If you click on the URL you can now see your webpage as hosted online. If you share this URL with others, they can now also see and access your webpage.

Congratulations, you have now created your first webpage and published it online!

The next steps now will be to customize your webpage. We will go over that in the next section.

Moving onward, you can create new pages and customize a lot. However, it is very important that you never change the name, move, or delete the _quarto.yml, index.qmd, and docs folder (if hosting the webpage on GitHub). You would also likely want the styles.css file to get the right layout of your pages.

One thing that is cool with your webpage, is that it will automatically update the layout to work on mobile phones, so you can create your layout the way you want it on the computer and then Quarto customize it again to work on a mobile phone as necessary.


SOURCES:
- Building the webpage manually in Rmarkdown instead of with Quarto - [Link](https://lisalendway.netlify.app/posts/2021-08-18-quicksite/)
- Introduction to creating a Quarto webpage, hosting it on GitHub, and customizing the page - [Link](https://ucsb-meds.github.io/creating-quarto-websites/)
- Quarto's documentation on creating and customizing webpages - [Link](https://quarto.org/docs/websites/)
- How to connect the R project and GitHub if you create the R project first - [Link](https://happygitwithr.com/existing-github-last.html)
- Instructions on how to host the webpage on GitHub - [Link](https://github.com/DataScience4Psych/template_portfolio)
